/**
 * Transparent Earnings Calculator — GarvecoRewards
 *
 * Every action (ad, survey, offer) generates a gross value.
 * - 70% goes to the user
 * - 30% goes to platform administration
 *
 * All values are in coins (100 coins = $1.00 USD)
 *
 * IMPORTANT: No fixed coin amounts are used here.
 * All gross values must be passed dynamically from real ad/survey/offer callbacks.
 * The ACTION_GROSS_VALUES below are ONLY reference estimates for UI previews;
 * actual rewards must always come from real platform callbacks.
 */

export const PLATFORM_SPLIT = {
  USER_SHARE: 0.70,
  PLATFORM_SHARE: 0.30,
} as const;

export interface EarningsBreakdown {
  grossCoins: number;       // Total generated by the action
  userCoins: number;        // 70% — credited to user
  platformCoins: number;    // 30% — kept by platform
  userPercent: number;      // Always 70
  platformPercent: number;  // Always 30
  usdValue: string;         // User's USD equivalent
}

/**
 * Calculate the transparent 70/30 earnings breakdown for any action.
 * @param grossCoins - The total coins the action generates (must come from real platform data)
 */
export function calculateEarnings(grossCoins: number): EarningsBreakdown {
  const userCoins = Math.floor(grossCoins * PLATFORM_SPLIT.USER_SHARE);
  const platformCoins = grossCoins - userCoins;
  const usdValue = (userCoins * 0.01).toFixed(2);

  return {
    grossCoins,
    userCoins,
    platformCoins,
    userPercent: 70,
    platformPercent: 30,
    usdValue,
  };
}

/**
 * Reference gross coin estimates per action type.
 * These are ONLY used for UI preview labels before a real callback fires.
 * The actual reward credited to the user MUST come from the real ad/survey/offer
 * callback (e.g., Unity Ads onRewardGranted, TheoremReach webhook, PropellerAds
 * postback, Monetag callback, etc.).
 *
 * Formula: userCoins = Math.floor(realGrossFromPlatform * 0.70)
 */
export const ACTION_GROSS_VALUES = {
  // Rewarded video ad — estimate only; real value from Unity/PropellerAds callback
  rewardedAd: 100,
  // Short video ad — estimate only
  shortVideo: 70,
  // Sponsored article read — estimate only
  articleRead: 57,
  // Brief survey (5 questions) — estimate only; real value from survey callback
  briefSurvey: 170,
  // Premium brand survey (15 min) — estimate only
  premiumSurvey: 500,
  // Referral bonus — estimate only
  referral: 285,
  // Daily login bonus — estimate only
  dailyBonus: 100,
  // TheoremReach survey/offer — always 0 here; real value from webhook reward field
  theoremReach: 0,
  // PropellerAds / Monetag — always 0 here; real value from postback callback
  propellerAds: 0,
  monetag: 0,
} as const;

/**
 * Format a breakdown for display in the UI.
 */
export function formatBreakdownLabel(breakdown: EarningsBreakdown): string {
  return `Generado: ${breakdown.grossCoins} 🪙 · Tú recibes: ${breakdown.userPercent}% (${breakdown.userCoins} 🪙) · Plataforma: ${breakdown.platformPercent}% (${breakdown.platformCoins} 🪙)`;
}
